// Auto-generated Embedded Static Registry for Cloudflare Workers & Edge Environments
export const STATIC_MOVIE_FILES: Record<string, string> = {
  "video\\evil-dead-burn.md": "---\ntmdb_id: 1212763\nvideourl: >-\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\ntitle: Evil Dead Burn\nimage_url: 'https://image.tmdb.org/t/p/w1280/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg'\nrating: 8.5\nfeatured: true\ntrending: true\nlanguage: EN\n---\n\n",
  "video\\rage-of-stars.md": "---\r\ntmdb_id: 1323244\r\nvideourl: >-\r\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\r\ntitle: Rage of Stars\r\ndeskripsi: >-\r\n  A story about a woman from the International Special Forces Unit, who has a\r\n  premonition about the impending end of humanity.\r\nrating: 5.6\r\n---\r\n\r\n",
  "video\\spider-man-brand-new-day.md": "---\r\ntmdb_id: 969681\r\nvideourl: >-\r\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\r\ntitle: 'Spider-Man: Brand New Day'\r\ndeskripsi: >-\r\n  Empat tahun setelah peristiwa Spider-Man: No Way Home, Peter Parker sudah\r\n  tidak ada lagi dan Spider-Man kini berada di puncak kemampuannya dalam menjaga\r\n  Kota New York tetap aman. Semuanya berjalan dengan baik hingga serangkaian\r\n  kejahatan yang tidak biasa menyeret Spider-Man ke dalam jaring misteri yang\r\n  lebih besar dari apa pun yang pernah ia hadapi sebelumnya. Untuk menghadapi\r\n  apa yang akan datang, Spider-Man tidak hanya harus berada dalam kondisi fisik\r\n  dan mental terbaiknya, tetapi juga harus siap menghadapi konsekuensi dari masa\r\n  lalunya!\r\nimage_url: 'https://image.tmdb.org/t/p/w500/bjiS5ipwxb9JFy3XRRN4OAilSeX.jpg'\r\nrating: 0\r\n---\r\n\r\n",
  "video\\the-last-sunrise.md": "---\r\ntmdb_id: 1516698\r\nvideourl: >-\r\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\r\ntitle: The Last Sunrise\r\ndeskripsi: >-\r\n  Ry, a college student with a chronic illness, escapes to Mallorca for the\r\n  summer with her mother, where she unexpectedly falls for a local and begins to\r\n  embrace living in the moment. But as her condition worsens and long-hidden\r\n  family secrets come to light, everything she has found before summer's end is\r\n  threatened.\r\nimage_url: 'https://image.tmdb.org/t/p/w1280/dJdZcLn8t1ZLodoxaP4DJ6jgBKy.jpg'\r\nrating: 7.9\r\nfeatured: true\r\n---\r\n\r\n"
};

export const STATIC_TV_FILES: Record<string, string> = {
  "tv\\bleach\\s1\\e1.md": "---\r\nvideourl: >-\r\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\r\ntitle: Episode 1\r\nimage_url: 'https://image.tmdb.org/t/p/w500/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg'\r\nrating: 0\r\n---\r\n\r\n",
  "tv\\bleach\\_index.md": "---\r\ntmdb_id: 30984\r\ntitle: Bleach\r\ndeskripsi: >-\r\n  For as long as he can remember, Ichigo Kurosaki has been able to see ghosts.\r\n  But when he meets Rukia, a Soul Reaper who battles evil spirits known as\r\n  Hollows, he finds his life is changed forever. Now, with a newfound wealth of\r\n  spiritual energy, Ichigo discovers his true calling: to protect the living and\r\n  the dead from evil.\r\nimage_url: 'https://image.tmdb.org/t/p/w500/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg'\r\nrating: 0\r\nfeatured: true\r\n---\r\n\r\n",
  "tv\\lanterns\\s1\\e1.md": "---\nvideourl: >-\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\ntitle: e1\nimage_url: 'https://image.tmdb.org/t/p/original/jMCAu91V7fsnHNUvabOPMBLaLaj.jpg'\nrating: 0\n---\n\r\n",
  "tv\\lanterns\\s1\\e2.md": "---\nvideourl: >-\n  https://huggingface.co/buckets/nexus33rd/cloud/resolve/BLEACH.Thousand.Year.Blood.War.S01E45.1080p.NF.WEB-DL.AAC2.0.H.264-VARYG.mkv\ntitle: 'Episode 2: Sector 2814'\nimage_url: 'https://image.tmdb.org/t/p/original/jMCAu91V7fsnHNUvabOPMBLaLaj.jpg'\nrating: 0\n---\n\r\n",
  "tv\\lanterns\\s1\\e3.md": "---\nvideourl: >-\n  https://download.levistream.web.id/drive/api/download?id=1Wp0ZxND28usuMWBX6qNessRA9DyVGXVN\ntitle: Episode 3\nimage_url: 'https://image.tmdb.org/t/p/w1280/ruwzidqanSyhhMEk6kCVd9BLui1.jpg'\nrating: 0\n---\n\r\n",
  "tv\\lanterns\\_index.md": "---\ntmdb_id: 95350\ntitle: Lanterns\ndeskripsi: >-\n  Dua polisi antargalaksi, rekrutan baru John Stewart dan legenda Green Lantern\n  Hal Jordan, terseret ke dalam misteri gelap di Bumi saat mereka menyelidiki\n  kasus pembunuhan di jantung Amerika.\nimage_url: 'https://image.tmdb.org/t/p/w1280/ruwzidqanSyhhMEk6kCVd9BLui1.jpg'\nrating: 8.2\nfeatured: true\n---\n\r\n",
  "tv\\shogun\\s1\\e1.md": "---\nvideourl: >-\n  https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4\ntitle: 'Chapter One: Anjin'\ndeskripsi: >-\n  Kapal Belanda yang terdampar di pesisir Jepang membawa navigator Inggris John\n  Blackthorne ke dalam pusaran politik berbahaya.\nimage_url: 'https://image.tmdb.org/t/p/w780/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg'\nrating: 9.9\nduration: 65m\n---\n\r\n### 🌊 Chapter One: Anjin\r\nKedatangan John Blackthorne di desa nelayan Ajiro menjadi awal pergeseran kekuasaan politik di era feodal Jepang.\r\n",
  "tv\\shogun\\_index.md": "---\ntmdb_id: 126308\ntitle: Shōgun (Limited Series Edition)\ndeskripsi: >-\n  Di Jepang abad ke-17 pada masa awal perang saudara yang menentukan abad\n  tersebut, Lord Yoshii Toranaga berjuang untuk bertahan hidup ketika\n  musuh-musuhnya di Dewan Bupati bersatu melawannya.\nimage_url: 'https://image.tmdb.org/t/p/w1280/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg'\nrating: 9.9\n---\n\r\n# ⚔️ Shōgun - Limited Series Edition (Flat Episode Layout)\r\n\r\nHalaman ini mendemonstrasikan **Flat Episode Structure** tanpa folder season (`tv/shogun/e1.md`, `tv/shogun/e2.md`), sehingga halaman otomatis menampilkan daftar episode tanpa nomor/tab season.\r\n",
  "tv\\stranger-things\\s1\\e1.md": "---\nvideourl: 'https://ryuzakinear211.github.io/video/video'\ntitle: 'Chapter One: The Vanishing of Will Byers'\ndeskripsi: >-\n  Dalam perjalanan pulang dari rumah temannya, Will Byers melihat sesuatu yang\n  mengerikan. Di dekatnya, laboratorium rahasia menyimpan misteri kelam.\nimage_url: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg'\nrating: 9.5\n---\n\r\n",
  "tv\\stranger-things\\s1\\e2.md": "---\nvideourl: 'https://ryuzakinear211.github.io/video/video'\ntitle: 'Chapter Two: The Weirdo on Maple Street'\ndeskripsi: >-\n  Lucas, Mike, dan Dustin mencoba berbicara dengan gadis misterius yang mereka\n  temukan di hutan. Kepala Polisi Hopper menyelidiki kejanggalan di\n  laboratorium.\nimage_url: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg'\nrating: 9.4\n---\n\r\n",
  "tv\\stranger-things\\s2\\e1.md": "---\nvideourl: 'https://ryuzakinear211.github.io/video/video'\ntitle: 'Chapter One: MADMAX'\ndeskripsi: >-\n  Saat kota Hawkins bersiap untuk Halloween, seorang murid baru yang tangguh\n  tiba di sekolah, dan Will mengalami penglihatan mengerikan tentang bayangan\n  raksasa.\nimage_url: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg'\nrating: 9.6\n---\n\r\n",
  "tv\\stranger-things\\s2\\e2.md": "---\nvideourl: 'https://ryuzakinear211.github.io/video/video'\ntitle: 'Chapter Two: Trick or Treat, Freak'\ndeskripsi: >-\n  Setelah Will melihat sesuatu yang mengerikan di malam Halloween, Mike mulai\n  meragukan apakah Eleven masih berada di suatu tempat.\nimage_url: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg'\nrating: 9.5\n---\n\r\n",
  "tv\\stranger-things\\_index.md": "---\ntmdb_id: 66732\ntitle: Stranger Things\ndeskripsi: >-\n  Ketika seorang bocah laki-laki menghilang secara misterius, ibunya,\n  teman-temannya, dan kepala polisi setempat harus menghadapi kekuatan\n  supernatural mengerikan dan eksperimen rahasia pemerintah untuk membawanya\n  pulang.\nrating: 9.6\nfeatured: true\n---\n\r\n"
};
